swagger: "2.0"
info:
  version: "1.0.0"
  title: "Simple Artist API"
  description: An Simple API to understand the Swagger specification in greater details.
schemes: 
- https
host: example.io
basePath: /v1
securityDefinitions:
  UserSecurity:
    type: basic
security:
  - UserSecurity: []

  
paths: 
  /artists:
    get:
      description: returns the list of artists
      parameters:
        - $ref: '#/parameters/PageLimit'
        - $ref: '#/parameters/PageNumber'
          
      responses:
        200:
          description: Successfully returned the artists
          schema:
            type: array
            items: 
              $ref: '#/definitions/Artist'
        400:
          $ref: '#/responses/400Error'
        
    
    post:
      description: lets user to post a new artist
      parameters:
        - name: artist
          in: body
          description: Create a new artist in database
          schema:
            $ref: '#/definitions/Artist'
      responses:
        200:
          description: Successfully created a artist
        400:
          $ref: '#/responses/400Error'  
  /artist/{username}:
    get:
      description: Obtain information about an artist from his or her unique username
      parameters:
        - name: username
          in: path
          type: string
          required: true
      responses:
        200:
          description: successfully returned an artist
          schema:
            type: object
            properties:
              artist_name:
                type : string
              artitst_genre:
                type: string
              albums_recorded:
                type: integer
        400:
          description: Invalid request
          schema:
            type: object
            properties:
              message:
                type: string
definitions:
  Artist:
    type: object
    required:
     - username
    properties:
      artist_name:
        type : string
      artitst_genre:
        type: string
      albums_recorded:
        type: integer 
      username:
        type: string
parameters:
  PageLimit:
    name: limit
    in: query
    type: integer
    description: limits the number of items on a page
          
    
  PageNumber:
    name: offset
    in: query
    type: integer
    description: limits the number of artists to be displayed.
responses:
  400Error:
    description: Invalid request
    schema:
      type: object
      properties:
        message:
          type: string
